apiVersion: v1
kind: Service
metadata:
  name: my-app-lb
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80          # The port on which the service is exposed
      targetPort: 8080   # The port on the pods
  type: LoadBalancer     # This makes the service type LoadBalancer
